version: '3'

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabaseappdb"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=name"
      - "MB_DB_PASS=password"
      - "MB_DB_HOST=my-database-host"
    volumes:
      - ./metabase-data:/metabase-data
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: metabaseappdb
      POSTGRES_USER: name
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
