version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node-app
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "3021:5000"
    depends_on:
      - pgdata
    environment:
      PG_HOST: postgres-db2
      PG_PORT: 5432
      PG_USER: db
      PG_PASSWORD: db
      PG_DATABASE: db

  pgdata:
      image: postgres:latest
      container_name: postgres-db2
      environment:
        POSTGRES_USER: db
        POSTGRES_PASSWORD: db
        POSTGRES_DB: db
      ports:
        - "5433:5432"
      volumes:
        - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  frontend:
    image: nginx:latest
    container_name: web-frontend
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "80:80"
